---
# tasks file for wks-ops
# depends: wks-dev
- name: install programs
  apt: name={{item}} state=present update_cache=yes cache_valid_time=86400
  with_items:
    - nmap
    - whois
    - dig
    - mtr-tiny
    - sshfs
    - traceroute
    - system-config-kickstart
