## YAML Template.
---
tag: 0

users: users
dns: dns
fqdn: fqdn
subdomains: subdomains
tld: tld
folders: folders

cluster_name: "{{strata}}-ppm-clr"

users:
- {count: '0', username: 'netadmin', user_full: 'ppm systems', user_email: 'systems@prepaidmeters.com', groups: 'sudo',
   shell: '/bin/bash', sshkey_pvt: '{{ netadmin_id_rsa }}', sshkey_pub: '{{ netadmin_id_rsa_pub }}'
    }
- {count: '1', username: 'sean', user_full: 'Sean Wheller', user_email: 'sean@prepaidmeters.com', groups: 'sudo',
   shell: '/bin/bash', sshkey_pvt: '{{ sean_id_rsa }}', sshkey_pub: '{{ sean_id_rsa_pub }}'
    }
- {count: '2', username: 'tofara', user_full: 'Tofara Machemedze', user_email: 'tofara@prepaidmeters.com', groups: 'sudo',
   shell: '/bin/bash', sshkey_pvt: '{{ tofara_id_rsa }}', sshkey_pub: '{{ tofara_id_rsa_pub }}'
    }
- {count: '3', username: 'andries', user_full: 'Andries Esterhuizen', user_email: 'andries@prepaidmeters.com', groups: 'sudo',
   shell: '/bin/bash', sshkey_pvt: '{{ andries_id_rsa }}', sshkey_pub: '{{ andries_id_rsa_pub }}'
    }

networks:
- {count: '0', network: '192.168.0.0', netmask: '255.255.255.0', gateway: '192.168.0.1', broadcast: '192.168.0.255' }
- {count: '1', network: '192.168.239.0', netmask: '255.255.255.0', gateway: '192.168.239.1', broadcast: '192.168.239.255' }

dns:
- {count: '00', alias: "google_1_dns", ipaddress: "8.8.8.8"}
- {count: '01', alias: "google_2_dns", ipaddress: "8.8.4.4"}

fqdn:
- {count: '0', domain: "{{ subdomains }}.{{ strata }}[0].domain.{{ subdomains }}.{{ strata }}[0].domain.{{ tld }}.{{ strata }}[0].tld"}
- {count: '1', domain: "{{ subdomains }}.{{ strata }}[1].domain.{{ subdomains }}.{{ strata }}[0].domain.{{ tld }}.{{ strata }}[0].tld"}
- {count: '1', domain: "{{ subdomains }}.{{ strata }}[0].domain.{{ subdomains }}.{{ strata }}[0].domain.{{ tld }}.{{ strata }}[1].tld"}
- {count: '1', domain: "{{ subdomains }}.{{ strata }}[1].domain.{{ subdomains }}.{{ strata }}[0].domain.{{ tld }}.{{ strata }}[1].tld"}
- {count: '1', domain: "{{ subdomains }}.{{ strata }}[0].domain.{{ subdomains }}.{{ strata }}[0].domain.{{ tld }}.{{ strata }}[2].tld"}
- {count: '1', domain: "{{ subdomains }}.{{ strata }}[1].domain.{{ subdomains }}.{{ strata }}[0].domain.{{ tld }}.{{ strata }}[2].tld"}

domains:
- {count: '0', domain: "prepaidmeters"}

tld::
- {count: '0', tld: ".co.za"}
- {count: '1', tld: ".com"}
- {count: '2', tld: ".net"}

mounts:
- {count: '00', mntserver: '192.168.0.18', mnttarget: '/var/nfs', mntpoint: '/mnt/nfs/prd-ppm-file-0', mnttype: 'nfs'}
- {count: '01', mntserver: '192.168.239.5', mnttarget: '/var/nfs', mntpoint: '/mnt/nfs/prd-ppm-file-1', mnttype: 'nfs'}
- {count: '02', mntserver: '192.168.1.27', mnttarget: '/var/nfs', mntpoint: '/mnt/nfs/prd-ppm-file-jhb', mnttype: 'nfs'}
- {count: '03', mntserver: '192.168.0.18', mnttarget: '/var/nfs', mntpoint: '/mnt/nfs/prd-ppm-file-0', mnttype: 'nfs'}
- {count: '04', mntserver: '192.168.239.5', mnttarget: '/var/nfs', mntpoint: '/mnt/nfs/prd-ppm-file-1', mnttype: 'nfs'}
- {count: '05', mntserver: '192.168.1.27', mnttarget: '/var/nfs', mntpoint: '/mnt/nfs/prd-ppm-file-jhb', mnttype: 'nfs'}
- {count: '06', mntserver: '192.168.0.18', mnttarget: '/var/nfs', mntpoint: '/mnt/nfs/prd-ppm-file-0', mnttype: 'nfs'}
- {count: '07', mntserver: '192.168.239.5', mnttarget: '/var/nfs', mntpoint: '/mnt/nfs/prd-ppm-file-1', mnttype: 'nfs'}
- {count: '08', mntserver: '192.168.0.18', mnttarget: '/var/nfs', mntpoint: '/mnt/nfs/prd-ppm-file-0', mnttype: 'nfs'}
- {count: '09', mntserver: '192.168.239.5', mnttarget: '/var/nfs', mntpoint: '/mnt/nfs/prd-ppm-file-1', mnttype: 'nfs'}
- {count: '10', mntserver: '192.168.1.27', mnttarget: '/var/nfs', mntpoint: '/mnt/nfs/prd-ppm-file-jhb', mnttype: 'nfs'}
- {count: '11', mntserver: '192.168.1.16', mnttarget: '/volume1/prd', mntpoint: '/mnt/nfs/ppm-nas-1', mnttype: 'nfs'}
- {count: '12', mntserver: '192.168.1.16', mnttarget: '/volume1/prd', mntpoint: '/mnt/nfs/ppm-nas-1', mnttype: 'nfs'}
- {count: '13', mntserver: '192.168.1.16', mnttarget: '/volume1/prd', mntpoint: '/mnt/nfs/ppm-nas-1', mnttype: 'nfs'}
- {count: '14', mntserver: '192.168.0.18', mnttarget: '/var/nfs', mntpoint: '/mnt/nfs/prd-ppm-file-0', mnttype: 'nfs'}
- {count: '15', mntserver: '192.168.239.5', mnttarget: '/var/nfs', mntpoint: '/mnt/nfs/prd-ppm-file-1', mnttype: 'nfs'}
- {count: '16', mntserver: '192.168.1.27', mnttarget: '/var/nfs', mntpoint: '/mnt/nfs/prd-ppm-file-jhb', mnttype: 'nfs'}
- {count: '17', mntserver: '192.168.0.18', mnttarget: '/var/nfs', mntpoint: '/mnt/nfs/prd-ppm-file-0', mnttype: 'nfs'}
- {count: '18', mntserver: '192.168.239.5', mnttarget: '/var/nfs', mntpoint: '/mnt/nfs/prd-ppm-file-1', mnttype: 'nfs'}
- {count: '19', mntserver: '192.168.1.27', mnttarget: '/var/nfs', mntpoint: '/mnt/nfs/prd-ppm-file-jhb', mnttype: 'nfs'}
- {count: '20', mntserver: '192.168.0.18', mnttarget: '/var/nfs', mntpoint: '/mnt/nfs/prd-ppm-file-0', mnttype: 'nfs'}
- {count: '21', mntserver: '192.168.239.5', mnttarget: '/var/nfs', mntpoint: '/mnt/nfs/prd-ppm-file-1', mnttype: 'nfs'}
- {count: '22', mntserver: '192.168.0.18', mnttarget: '/var/nfs', mntpoint: '/mnt/nfs/prd-ppm-file-0', mnttype: 'nfs'}
- {count: '23', mntserver: '192.168.239.5', mnttarget: '/var/nfs', mntpoint: '/mnt/nfs/prd-ppm-file-1', mnttype: 'nfs'}

#hosts:
haproxy:
- {count: '0', hostname: 'prd-ppm-ha-0', ipaddress: '192.168.0.9', mac: '00:50:56:93:08:d6', ext_nat: '41.85.146.105'}
- {count: '1', hostname: 'prd-ppm-ha-1', ipaddress: '192.168.239.9', mac: '00:50:56:ab:34:33', ext_nat: 'none'}
- {count: '2', hostname: 'prd-ppm-ha-jhb', ipaddress: '192.168.1.24', mac: '56:55:54:53:01:24', ext_nat: 'none'}
apache2:
- {count: '0', hostname: 'prd-ppm-www-0', ipaddress: '192.168.0.20', mac: '00:50:56:01:01:0d', ext_nat: '41.85.146.110'}
- {count: '1', hostname: 'prd-ppm-www-1', ipaddress: '192.168.239.20', mac: '00:50:56:ab:40:23', ext_nat: 'none'}
- {count: '2', hostname: 'prd-ppm-www-jhb', ipaddress: '192.168.1.25', mac: '56:55:54:53:01:25', ext_nat: 'none'}
mariadb:
- {count: '0', hostname: 'prd-ppm-clr-0', ipaddress: '192.168.0.11', mac: '00:50:56:01:00:ec', ext_nat: 'none'}
- {count: '1', hostname: 'prd-ppm-clr-1', ipaddress: '192.168.239.11', mac: '00:50:56:ab:4f:4d', ext_nat: 'none'}
- {count: '2', hostname: 'prd-ppm-clr-2', ipaddress: '192.168.0.16', mac: '00:50:56:01:00:b0', ext_nat: 'none'}
- {count: '3', hostname: 'prd-ppm-clr-3', ipaddress: '192.168.239.4', mac: '00:50:56:ab:33:1c', ext_nat: 'none'}
- {count: '4', hostname: 'prd-ppm-clr-jhb', ipaddress: '192.168.1.26', mac: '56:55:54:53:01:26', ext_nat: 'none'}
file:
- {count: '0', hostname: 'prd-ppm-file-0', ipaddress: '192.168.0.18', mac: '00:50:56:01:00:b1', ext_nat: 'none'}
- {count: '1', hostname: 'prd-ppm-file-1', ipaddress: '192.168.239.5', mac: '00:50:56:ab:14:f2', ext_nat: 'none'}
- {count: '2', hostname: 'prd-ppm-file-jhb', ipaddress: '192.168.1.27', mac: '56:55:54:53:01:27', ext_nat: 'none'}
sts:
- {count: '0', hostname: 'prd-ppm-sts-0', ipaddress: '192.168.0.19', mac: '00:50:56:93:1d:15', ext_nat: 'none'}
- {count: '1', hostname: 'prd-ppm-sts-1', ipaddress: '192.168.239.19', mac: '00:50:56:ab:26:d9', ext_nat: 'none'}
- {count: '2', hostname: 'prd-ppm-sts-jhb', ipaddress: '192.168.1.28', mac: '56:55:54:53:01:28', ext_nat: 'none'}
infra:
- {count: '0', hostname: 'prd-ppm-infra-0', ipaddress: '192.168.0.12', mac: '00:50:56:01:00:f0', ext_nat: '41.85.145.20'}
- {count: '1', hostname: 'prd-ppm-infra-1', ipaddress: '192.168.239.12', mac: '00:50:56:ab:2f:f6', ext_nat: 'none'}
- {count: '2', hostname: 'prd-ppm-infra-jhb', ipaddress: '192.168.1.29', mac: '56:55:54:53:01:29', ext_nat: 'none'}
mail:
- {count: '0', hostname: 'prd-ppm-mail-0', ipaddress: '192.168.0.14', mac: '00:50:56:01:01:06', ext_nat: '41.85.145.19'}
- {count: '1', hostname: 'prd-ppm-mail-1', ipaddress: '192.168.239.???', mac: '', ext_nat: 'none'}
voip:
- {count: '0', hostname: 'prd-ppm-voip-0', ipaddress: '192.168.0.13', mac: '00:50:56:01:00:F4', ext_nat: '41.85.145.21'}
- {count: '1', hostname: 'prd-ppm-voip-1', ipaddress: '192.168.239.???', mac: '', ext_nat: 'none'}

folders:
- {count: "0", alias: "crescendo_folder", path: "/var/www/crescendo/webroot/webroot"}
- {count: "1", alias: "aurora_folder", path: "/var/www/aurora/"}
- {count: "2", alias: "erp_folder", path: "/var/www/erp/"}
- {count: "3", alias: "generic_folder", path: "/var/www/generic/"}
- {count: "4", alias: "blank", path: "blank"}
- {count: "5", alias: "blank", path: "blank"}
- {count: "6", alias: "blank", path: "blank"}
- {count: "7", alias: "documents_folder", path: "/mnt/nfs/var/nfs/prd-ppm-www-0/documents/trunk/"}
- {count: "8", alias: "documentsdynamic_folder", path: "/mnt/nfs/var/nfs/prd-ppm-www-0/documentsdynamic/"}
- {count: "9", alias: "devdatabasedestination_folder", path: "/var/www/generic/databasesamples/"}
- {count: "10", alias: "temp_folder", path: "/tmp/"}
- {count: "11", alias: "enbayacronrootlogdir_folder", path: "/var/log/enbaya/"}
- {count: "12", alias: "rsync_folder", path: "/run/ppm/"}
- {count: "13", alias: "backup_folder", path: "/var/backups/mysql/"}
- {count: "14", alias: "backuprestore_folder", path: "/var/backups/mysql/work/"}
- {count: "15", alias: "databasebackup_folder", path: "/var/rsync/db/"}
- {count: "16", alias: "devdatabasework_folder", path: "${devdatabasedestination_folder}/work/"}
- {count: "17", alias: "pathtovoicerecordings_folder", path: "/var/tmp"}
- {count: "18", alias: "impactftpdirectory_folder", path: "prepaid/"}
- {count: "19", alias: "devdocs_folder", path: "/opt/devdocs"}
- {count: "20", alias: "enbayasts_folder", path: "/var/www/enbayasts"}
- {count: "21", alias: "tcpdf_folder", path: "/var/www/tcpdf"}
- {count: "22", alias: "sugarcrm_folder", path: "/var/www/sugarcrm"}
- {count: "23", alias: "ppmwebsite_folder", path: "/var/www/ppmwebsite"}
- {count: "24", alias: "geo_folder", path: "/var/www/geo/"}

emails:
- {count: '0', alias: "systems_email", email: "systems@prepaidmeters.com"}
- {count: '1', alias: "sales_email", email: "sales@prepaidmeters.com"}
- {count: '2', alias: "support_email", email: "support@prepaidmeters.com"}
- {count: '3', alias: "testing_email", email: "testing@prepaidmeters.com"}
- {count: '4', alias: "development_email", email: "llewellyn@prepaidmeters.com"}
- {count: '5', alias: "accounts_email", email: "accounts@prepaidmeters.com"}
- {count: '6', alias: "accounts-warnings_email", email: "accounts-warnings@prepaidmeters.com"}
- {count: '7', alias: "product_email", email: "product@prepaidmeters.com"}
- {count: '8', alias: "alerts_email", email: "alerts@prepaidmeters.com"}
- {count: '9', alias: "backups_email", email: "backups@prepaidmeters.com"}
- {count: '10', alias: "tickets_email", email: "godfrey@prepaidmeters.com"}
- {count: '11', alias: "cigicell_email", email: "cigicell@prepaidmeters.com"}
- {count: '12', alias: "testing_email", email: "testing@prepaidmeters.co.co.za"}

smtp:
- {alias: "ppm_smtp", host: "mail.prepaidmeters.co.za", port: "25", user: "{{ ppm_smtp_user }}", password: "{{ ppm_smtp_pass }}", crypt: "tls", auth: "True"}

users_db:
- {alias: "user1", user: "{{user1_user}}", password: "{{prd_user1_pass}}", localhost: "localhost", remotehost: "%",  priv: "{{user1_priv}}"}
- {alias: "user2", user: "{{user2_user}}", password: "{{prd_user2_pass}}", localhost: "localhost", remotehost: "%",  priv: "{{user2_priv}}"}
- {alias: "user3", user: "{{user3_user}}", password: "{{prd_user3_pass}}", localhost: "localhost", remotehost: "%",  priv: "{{user3_priv}}"}
- {alias: "user4", user: "{{user4_user}}", password: "{{prd_user4_pass}}", localhost: "localhost", remotehost: "%",  priv: "{{user4_priv}}"}
- {alias: "user5", user: "{{user5_user}}", password: "{{prd_user5_pass}}", localhost: "localhost", remotehost: "%",  priv: "{{user5_priv}}"}
- {alias: "user6", user: "{{user6_user}}", password: "{{prd_user6_pass}}", localhost: "localhost", remotehost: "%",  priv: "{{user6_priv}}"}
- {alias: "user7", user: "{{user7_user}}", password: "{{prd_user7_pass}}", localhost: "localhost", remotehost: "%",  priv: "{{user7_priv}}"}
- {alias: "user8", user: "{{user8_user}}", password: "{{prd_user8_pass}}", localhost: "localhost", remotehost: "%",  priv: "{{user8_priv}}"}
- {alias: "user9", user: "{{user9_user}}", password: "{{prd_user9_pass}}", localhost: "localhost", remotehost: "%",  priv: "{{user9_priv}}"}
- {alias: "user10", user: "{{user10_user}}", password: "{{prd_user10_pass}}", localhost: "localhost", remotehost: "%",  priv: "{{user10_priv}}"}
- {alias: "user11", user: "{{user11_user}}", password: "{{prd_user11_pass}}", localhost: "localhost", remotehost: "%",  priv: "{{user11_priv}}"}
- {alias: "user12", user: "{{user12_user}}", password: "{{prd_user12_pass}}", localhost: "localhost", remotehost: "%",  priv: "{{user12_priv}}"}
- {alias: "user13", user: "{{user13_user}}", password: "{{prd_user13_pass}}", localhost: "localhost", remotehost: "%",  priv: "{{user13_priv}}"}
- {alias: "user14", user: "{{user14_user}}", password: "{{prd_user14_pass}}", localhost: "localhost", remotehost: "%",  priv: "{{user14_priv}}"}
- {alias: "user15", user: "{{user15_user}}", password: "{{prd_user15_pass}}", localhost: "localhost", remotehost: "%",  priv: "{{user15_priv}}"}
- {alias: "user16", user: "{{user16_user}}", password: "{{prd_user16_pass}}", localhost: "localhost", remotehost: "%",  priv: "{{user16_priv}}"}
- {alias: "user17", user: "{{user17_user}}", password: "{{prd_user17_pass}}", localhost: "localhost", remotehost: "%",  priv: "{{user17_priv}}"}
- {alias: "user18", user: "{{user18_user}}", password: "{{prd_user18_pass}}", localhost: "localhost", remotehost: "%",  priv: "{{user18_priv}}"}
- {alias: "user19", user: "{{user19_user}}", password: "{{prd_user19_pass}}", localhost: "localhost", remotehost: "%",  priv: "{{user19_priv}}"}

usernames_external:
- {alias: "git_hub_user", username: "ppmsystems"}
- {alias: "impact_ftp_user", username: "water"}
- {alias: "clickatell_aurora_mobile_user", username: "clickatellws"}
- {alias: "cigicell_aurora_mobile_user", username: "cigicellws"}
- {alias: "impact_id_user", username: "45602"}

usernames_internal:
- {alias: "crm_soap_user", username: "netmin"}
- {alias: "route_sms_user", username: "prepaidsms"}
- {alias: "hexing_webservice_user", username: "juice"}
- {alias: "enbayasts_user", username: "enbayasts"}