## YAML Template.
---
authkeys:
  prd:
    external:
    - {alias: "netcash_account_key", key: "{{ netcash_account_key }}"}
    - {alias: "netcash_debit_order_key", key: "{{ netcash_debit_order_key }}"}
    - {alias: "netcash_creditor_payment_key", key: "{{ netcash_creditor_payment_key }}"}
    - {alias: "getresponse_api_key", key: "{{ getresponse_api_key }}"}
    google:
    - {alias: "propertyware_google_key", key: "{{ propertyware_google_key }}", secret: "{{ propertyware_google_secret }}", option: ""}
    - {alias: "google_plus_key", key: "{{ google_plus_key }}", secret: "{{ google_plus_secret }}",  option: ""}
    facebook:
    - {alias: "propertyware_facebook_key", key: "{{ propertyware_facebook_key }}", secret: "{{ propertyware_facebook_secret }}"}
  stg:
    external:
    - {alias: "netcash_account_key", key: "{{ netcash_account_key }}"}
    - {alias: "netcash_debit_order_key", key: "{{ netcash_debit_order_key }}"}
    - {alias: "netcash_creditor_payment_key", key: "{{ netcash_creditor_payment_key }}"}
    - {alias: "getresponse_api_key", key: "{{ getresponse_api_key }}"}
    google:
    - {alias: "propertyware_google_key", key: "{{ propertyware_google_key }}", secret: "{{ propertyware_google_secret }}", option: ""}
    - {alias: "google_plus_key", key: "{{ google_plus_key }}", secret: "{{ google_plus_secret }}",  option: ""}
    facebook:
    - {alias: "propertyware_facebook_key", key: "{{ propertyware_facebook_key }}", secret: "{{ propertyware_facebook_secret }}"}
  tst:
    external:
    - {alias: "netcash_account_key", key: "{{ netcash_account_key }}"}
    - {alias: "netcash_debit_order_key", key: "{{ netcash_debit_order_key }}"}
    - {alias: "netcash_creditor_payment_key", key: "{{ netcash_creditor_payment_key }}"}
    - {alias: "getresponse_api_key", key: "{{ getresponse_api_key }}"}
    google:
    - {alias: "propertyware_google_key", key: "{{ propertyware_google_key }}", secret: "{{ propertyware_google_secret }}", option: ""}
    - {alias: "google_plus_key", key: "{{ google_plus_key }}", secret: "{{ google_plus_secret }}",  option: ""}
    facebook:
    - {alias: "propertyware_facebook_key", key: "{{ propertyware_facebook_key }}", secret: "{{ propertyware_facebook_secret }}"}
  dev:
    external:
    - {alias: "netcash_account_key", key: "{{ netcash_account_key }}"}
    - {alias: "netcash_debit_order_key", key: "{{ netcash_debit_order_key }}"}
    - {alias: "netcash_creditor_payment_key", key: "{{ netcash_creditor_payment_key }}"}
    - {alias: "getresponse_api_key", key: "{{ getresponse_api_key }}"}
    google:
    - {alias: "propertyware_google_key", key: "{{ propertyware_google_key }}", secret: "{{ propertyware_google_secret }}", option: ""}
    - {alias: "google_plus_key", key: "{{ google_plus_key }}", secret: "{{ google_plus_secret }}",  option: ""}
    facebook:
    - {alias: "propertyware_facebook_key", key: "{{ propertyware_facebook_key }}", secret: "{{ propertyware_facebook_secret }}"}