## YAML Template.
---
webservices:
  prd:
  - {alias: "vcs_webservice", user: "{{ vcs_webservice_user }}", password: "{{ vcs_webservice_pass }}"}
  stg:
  - {alias: "vcs_webservice", user: "{{ vcs_webservice_user }}", password: "{{ vcs_webservice_pass }}"}
  tst:
  - {alias: "vcs_webservice", user: "{{ vcs_webservice_user }}", password: "{{ vcs_webservice_pass }}"}
  dev:
  - {alias: "vcs_webservice", user: "{{ vcs_webservice_user }}", password: "{{ vcs_webservice_pass }}"}