## YAML Template.
---
passwords:
  prd:
  - {alias: "getresponse_password", password: "{{ getresponse_pass }}"}
  - {alias: "netcash_email_password", password: "{{ netcashemail_pass }}"}
  - {alias: "route_sms_password", password: "{{ routesms_pass }}"}
  - {alias: "clickatell_aurora_user_password", password: "{{ clickatellaurorauser_pass }}"}
  - {alias: "hexing_web_service_password", password: "{{ hexingwebservice_pass }}"}
  - {alias: "cigicell_aurora_user_password", password: "{{ cigicellaurorausers_pass }}"}
  - {alias: "impact_ftp_password", password: "{{ impactftp_pass }}"}
  - {alias: "crm_soap_password", password: "{{ crmsoap_pass }}"}
  - {alias: "absa_aurora_user_password", password: "{{ absaaurorausers_pass }}"}
  - {alias: "iap_aurora_user_password", password: "{{ iapaurorausers_pass }}"}
  - {alias: "tickets_email_password", password: "{{ ticketsemail_pass }}"}
  - {alias: "aurora_user_password", password: "{{ prd_aurora_user_pass }}"}
  - {alias: "testing_user_password", password: "{{ prd_testing_user_pass }}"}
  - {alias: "enbayasts_user_password", password: "{{ prd_enbayasts_user_pass }}"}
  stg:
  - {alias: "getresponse_password", password: "{{ getresponse_pass }}"}
  - {alias: "netcash_email_password", password: "{{ netcashemail_pass }}"}
  - {alias: "route_sms_password", password: "{{ routesms_pass }}"}
  - {alias: "clickatell_aurora_user_password", password: "{{ clickatellaurorauser_pass }}"}
  - {alias: "hexing_web_service_password", password: "{{ hexingwebservice_pass }}"}
  - {alias: "cigicell_aurora_user_password", password: "{{ cigicellaurorausers_pass }}"}
  - {alias: "impact_ftp_password", password: "{{ impactftp_pass }}"}
  - {alias: "crm_soap_password", password: "{{ crmsoap_pass }}"}
  - {alias: "absa_aurora_user_password", password: "{{ absaaurorausers_pass }}"}
  - {alias: "iap_aurora_user_password", password: "{{ iapaurorausers_pass }}"}
  - {alias: "tickets_email_password", password: "{{ ticketsemail_pass }}"}
  - {alias: "aurora_user_password", password: "{{ dev_aurora_user_pass }}"}
  - {alias: "testing_user_password", password: "{{ stg_testing_user_pass }}"}
  - {alias: "enbayasts_user_password", password: "{{ stg_enbayasts_user_pass }}"}
  tst:
  - {alias: "getresponse_password", password: "{{ getresponse_pass }}"}
  - {alias: "netcash_email_password", password: "{{ netcashemail_pass }}"}
  - {alias: "route_sms_password", password: "{{ routesms_pass }}"}
  - {alias: "clickatell_aurora_user_password", password: "{{ clickatellaurorauser_pass }}"}
  - {alias: "hexing_web_service_password", password: "{{ hexingwebservice_pass }}"}
  - {alias: "cigicell_aurora_user_password", password: "{{ cigicellaurorausers_pass }}"}
  - {alias: "impact_ftp_password", password: "{{ impactftp_pass }}"}
  - {alias: "crm_soap_password", password: "{{ crmsoap_pass }}"}
  - {alias: "absa_aurora_user_password", password: "{{ absaaurorausers_pass }}"}
  - {alias: "iap_aurora_user_password", password: "{{ iapaurorausers_pass }}"}
  - {alias: "tickets_email_password", password: "{{ ticketsemail_pass }}"}
  - {alias: "aurora_user_password", password: "{{ dev_aurora_user_pass }}"}
  - {alias: "testing_user_password", password: "{{ tst_testing_user_pass }}"}
  - {alias: "enbayasts_user_password", password: "{{ tst_enbayasts_user_pass }}"}
  dev:
  - {alias: "getresponse_password", password: "{{ getresponse_pass }}"}
  - {alias: "netcash_email_password", password: "{{ netcashemail_pass }}"}
  - {alias: "route_sms_password", password: "{{ routesms_pass }}"}
  - {alias: "clickatell_aurora_user_password", password: "{{ clickatellaurorauser_pass }}"}
  - {alias: "hexing_web_service_password", password: "{{ hexingwebservice_pass }}"}
  - {alias: "cigicell_aurora_user_password", password: "{{ cigicellaurorausers_pass }}"}
  - {alias: "impact_ftp_password", password: "{{ impactftp_pass }}"}
  - {alias: "crm_soap_password", password: "{{ crmsoap_pass }}"}
  - {alias: "absa_aurora_user_password", password: "{{ absaaurorausers_pass }}"}
  - {alias: "iap_aurora_user_password", password: "{{ iapaurorausers_pass }}"}
  - {alias: "tickets_email_password", password: "{{ ticketsemail_pass }}"}
  - {alias: "aurora_user_password", password: "{{ dev_aurora_user_pass }}"}
  - {alias: "testing_user_password", password: "{{ dev_testing_user_pass }}"}
  - {alias: "enbayasts_user_password", password: "{{ dev_enbayasts_user_pass }}"}

