---
# tasks file for host

- name: change hosts file
  template: src=hosts.j2 dest=/etc/hosts owner=root group=root mode=0644
  notify: set hostname

- name: change hostname file
  template: src=hostname.j2 dest=/etc/hostname owner=root group=root mode=0644
  
- name: interfaces file (dhcp)
  template: src=interfaces-dhcp.j2 dest=/etc/network/interfaces owner=root 
    group=root mode=0644
  when: ip_allocation == "dhcp"

- name: interfaces file (static)
  template: src=interfaces-static.j2 dest=/etc/network/interfaces owner=root 
    group=root mode=0644
  when: ip_allocation == "static"
  
- name: interfaces file (static bridge)
  template: src=interfaces-static-bridge.j2 dest=/etc/network/interfaces owner=root 
    group=root mode=0644
  when: ip_allocation == "static-bridge"

- name: improve ipsecurity
  template: src=10-network-security.conf.j2 
    dest=/etc/sysctl.d/10-network-security.conf owner=root group=root mode=0644
  notify: procps restart

- name: check procps up
  service: name=procps state=restarted enabled=true
