---
# tasks file for squid-deb-proxy
- name: squid-deb-proxy install (server)
  apt: name={{ item }} state=present update_cache=true cache_valid_time=86400
  with_items:
    - squid-deb-proxy
  when: inventory_hostname in groups.squid_deb_proxy

- name: squid-deb-proxy install (client)
  apt: name={{ item }} state=present update_cache=true cache_valid_time=86400
  with_items:
    - squid-deb-proxy-client

- name: create include directory
  file: path=/etc/squid-deb-proxy/{{ item }} owner=root group=root mode=0755
    state=directory
  with_items:
    - allowed-networks-src.acl.d
    - mirror-dstdomain.acl.d
    - pkg-blacklist.d
  when: inventory_hostname in groups.squid_deb_proxy

- name: add allowed-networks-src.acl
  template: src=allowed-networks-src.acl.j2
            dest=/etc/squid-deb-proxy/allowed-networks-src.acl
  when: "inventory_hostname in groups.squid_deb_proxy" 

- name: add allowed-networks-src.acl.d/10-default
  template: src=allowed-networks-src.acl.d.10-default.j2
            dest=/etc/squid-deb-proxy/allowed-networks-src.acl.d/10-default
  when: "inventory_hostname in groups.squid_deb_proxy" 
  
- name: add mirror-dstdomain.acl
  template: src=mirror-dstdomain.acl.j2
            dest=/etc/squid-deb-proxy/mirror-dstdomain.acl
  when: "inventory_hostname in groups.squid_deb_proxy" 
  
- name: add mirror-dstdomain.acl.d/10-default
  template: src=mirror-dstdomain.acl.d.10-default.j2
            dest=/etc/squid-deb-proxy/mirror-dstdomain.acl.d/10-default
  when: "inventory_hostname in groups.squid_deb_proxy" 

- name: add pkg-blacklist.d/10-default
  template: src=pkg-blacklist.d.10-default.j2
            dest=/etc/squid-deb-proxy/pkg-blacklist.d/10-default
  when: "inventory_hostname in groups.squid_deb_proxy" 

- name: deploy squid-deb-proxy.conf
  template: src=squid-deb-proxy.conf.j2
            dest=/etc/squid-deb-proxy/squid-deb-proxy.conf
  when: "inventory_hostname in groups.squid_deb_proxy" 
  notify: squid-deb-proxy restart

- name: squid-deb-proxy status
  service: name=squid-deb-proxy state=restarted enabled=true
  when: "inventory_hostname in groups.squid_deb_proxy" 
  
