## YAML Template.
---
tag: 0

users: users
dns: dns
fqdn: fqdn
subdomains: subdomains
tld: tld
folders: folders

cluster_name: "{{strata}}-ppm-clr"

users:
- {count: '0', username: 'netadmin', user_full: 'ppm systems', user_email: 'systems@prepaidmeters.com', groups: 'sudo',
   shell: '/bin/bash', sshkey_pvt: '{{ netadmin_id_rsa }}', sshkey_pub: '{{ netadmin_id_rsa_pub }}'
    }
- {count: '1', username: 'sean', user_full: 'Sean Wheller', user_email: 'sean@prepaidmeters.com', groups: 'sudo',
   shell: '/bin/bash', sshkey_pvt: '{{ sean_id_rsa }}', sshkey_pub: '{{ sean_id_rsa_pub }}'
    }
- {count: '2', username: 'tofara', user_full: 'Tofara Machemedze', user_email: 'tofara@prepaidmeters.com', groups: 'sudo',
   shell: '/bin/bash', sshkey_pvt: '{{ tofara_id_rsa }}', sshkey_pub: '{{ tofara_id_rsa_pub }}'
    }
- {count: '3', username: 'andries', user_full: 'Andries Esterhuizen', user_email: 'andries@prepaidmeters.com', groups: 'sudo',
   shell: '/bin/bash', sshkey_pvt: '{{ andries_id_rsa }}', sshkey_pub: '{{ andries_id_rsa_pub }}'
    }

dns:
- {count: '00', alias: "google_1_dns", ipaddress: "8.8.8.8"}
- {count: '01', alias: "google_2_dns", ipaddress: "8.8.4.4"}

fqdn:
- {count: '0', domain: "{{ subdomains }}.{{ strata }}[0].domain.{{ domains }}.{{ strata }}[0].domain.{{ tld }}.{{ strata }}[0].tld"}
- {count: '1', domain: "{{ subdomains }}.{{ strata }}[1].domain.{{ domains }}.{{ strata }}[0].domain.{{ tld }}.{{ strata }}[0].tld"}

subdomains:
- {count: '0', domain: "www"}
- {count: '1', domain: "mail"}
  
domains:
- {count: '0', domain: "prepaidmeters"}

tld::
- {count: '0', tld: ".local"}

folders:
- {count: "0", alias: "crescendo_folder", path: "/var/www/crescendo/webroot/webroot"}
- {count: "1", alias: "aurora_folder", path: "/var/www/aurora/"}
- {count: "2", alias: "erp_folder", path: "/var/www/erp/"}
- {count: "3", alias: "generic_folder", path: "/var/www/generic/"}
- {count: "4", alias: "blank", path: "blank"}
- {count: "5", alias: "blank", path: "blank"}
- {count: "6", alias: "blank", path: "blank"}
- {count: "7", alias: "documents_folder", path: "/mnt/nfs/var/nfs/prd-ppm-www-0/documents/trunk/"}
- {count: "8", alias: "documentsdynamic_folder", path: "/mnt/nfs/var/nfs/prd-ppm-www-0/documentsdynamic/"}
- {count: "9", alias: "devdatabasedestination_folder", path: "/var/www/generic/databasesamples/"}
- {count: "10", alias: "temp_folder", path: "/tmp/"}
- {count: "11", alias: "enbayacronrootlogdir_folder", path: "/var/log/enbaya/"}
- {count: "12", alias: "rsync_folder", path: "/run/ppm/"}
- {count: "13", alias: "backup_folder", path: "/var/backups/mysql/"}
- {count: "14", alias: "backuprestore_folder", path: "/var/backups/mysql/work/"}
- {count: "15", alias: "databasebackup_folder", path: "/var/rsync/db/"}
- {count: "16", alias: "devdatabasework_folder", path: "${devdatabasedestination_folder}/work/"}
- {count: "17", alias: "pathtovoicerecordings_folder", path: "/var/tmp"}
- {count: "18", alias: "impactftpdirectory_folder", path: "prepaid/"}
- {count: "19", alias: "devdocs_folder", path: "/opt/devdocs"}
- {count: "20", alias: "enbayasts_folder", path: "/var/www/enbayasts"}
- {count: "21", alias: "tcpdf_folder", path: "/var/www/tcpdf"}
- {count: "22", alias: "sugarcrm_folder", path: "/var/www/sugarcrm"}
- {count: "23", alias: "ppmwebsite_folder", path: "/var/www/ppmwebsite"}
- {count: "24", alias: "geo_folder", path: "/var/www/geo/"}
  
#emails:


smtp:
- {alias: "ppm_smtp", host: "mail.prepaidmeters.co.za", port: "25", user: "{{ ppm_smtp_user }}", password: "{{ ppm_smtp_pass }}", crypt: "tls", auth: "True"}

users_db:
- {alias: "user1", user: "{{user1_user}}", password: "{{dev_user1_pass}}", localhost: "localhost", remotehost: "%",  priv: "{{user1_priv}}"}
- {alias: "user2", user: "{{user2_user}}", password: "{{dev_user2_pass}}", localhost: "localhost", remotehost: "%",  priv: "{{user2_priv}}"}
- {alias: "user3", user: "{{user3_user}}", password: "{{dev_user3_pass}}", localhost: "localhost", remotehost: "%",  priv: "{{user3_priv}}"}
- {alias: "user4", user: "{{user4_user}}", password: "{{dev_user4_pass}}", localhost: "localhost", remotehost: "%",  priv: "{{user4_priv}}"}
- {alias: "user5", user: "{{user5_user}}", password: "{{dev_user5_pass}}", localhost: "localhost", remotehost: "%",  priv: "{{user5_priv}}"}
- {alias: "user6", user: "{{user6_user}}", password: "{{dev_user6_pass}}", localhost: "localhost", remotehost: "%",  priv: "{{user6_priv}}"}
- {alias: "user7", user: "{{user7_user}}", password: "{{dev_user7_pass}}", localhost: "localhost", remotehost: "%",  priv: "{{user7_priv}}"}
- {alias: "user8", user: "{{user8_user}}", password: "{{dev_user8_pass}}", localhost: "localhost", remotehost: "%",  priv: "{{user8_priv}}"}
- {alias: "user9", user: "{{user9_user}}", password: "{{dev_user9_pass}}", localhost: "localhost", remotehost: "%",  priv: "{{user9_priv}}"}
- {alias: "user10", user: "{{user10_user}}", password: "{{dev_user10_pass}}", localhost: "localhost", remotehost: "%",  priv: "{{user10_priv}}"}
- {alias: "user11", user: "{{user11_user}}", password: "{{dev_user11_pass}}", localhost: "localhost", remotehost: "%",  priv: "{{user11_priv}}"}
- {alias: "user12", user: "{{user12_user}}", password: "{{dev_user12_pass}}", localhost: "localhost", remotehost: "%",  priv: "{{user12_priv}}"}
- {alias: "user13", user: "{{user13_user}}", password: "{{dev_user13_pass}}", localhost: "localhost", remotehost: "%",  priv: "{{user13_priv}}"}
- {alias: "user14", user: "{{user14_user}}", password: "{{dev_user14_pass}}", localhost: "localhost", remotehost: "%",  priv: "{{user14_priv}}"}
- {alias: "user15", user: "{{user15_user}}", password: "{{dev_user15_pass}}", localhost: "localhost", remotehost: "%",  priv: "{{user15_priv}}"}
- {alias: "user16", user: "{{user16_user}}", password: "{{dev_user16_pass}}", localhost: "localhost", remotehost: "%",  priv: "{{user16_priv}}"}
- {alias: "user17", user: "{{user17_user}}", password: "{{dev_user17_pass}}", localhost: "localhost", remotehost: "%",  priv: "{{user17_priv}}"}
- {alias: "user18", user: "{{user18_user}}", password: "{{dev_user18_pass}}", localhost: "localhost", remotehost: "%",  priv: "{{user18_priv}}"}
- {alias: "user19", user: "{{user19_user}}", password: "{{dev_user19_pass}}", localhost: "localhost", remotehost: "%",  priv: "{{user19_priv}}"}

usernames_external:
- {alias: "git_hub_user", username: "ppmsystems"}
- {alias: "impact_ftp_user", username: "water"}
- {alias: "clickatell_aurora_mobile_user", username: "clickatellws"}
- {alias: "cigicell_aurora_mobile_user", username: "cigicellws"}
- {alias: "impact_id_user", username: "45602"}

usernames_internal:
- {alias: "crm_soap_user", username: "netmin"}
- {alias: "route_sms_user", username: "prepaidsms"}
- {alias: "hexing_webservice_user", username: "juice"}
- {alias: "enbayasts_user", username: "enbayasts"}
