---
# tasks file for openvpn
# see meta/mail.xml for dependancies

- name: openvpn install
  apt: name=openvpn state=present update_cache=true cache_valid_time=86400

- name: enable ipv4 forwaring (etc/sysctl.conf)
  command: echo 1 > /proc/sys/net/ipv4/ip_forward  

- name: ensure ipv4 forward persistant (/proc/sys/net/ipv4/ip_forward)
  lineinfile: dest=/etc/sysctl.conf regexp="^net.ipv4.ip_forward" 
    line="net.ipv4.ip_forward=1"

#- name: ensure the client config directory is present
#  file: path=/etc/openvpn/ccd state=directory owner=root group=root mode=0644

- name: deploy openvpn server.conf
  template: src=server.conf.j2 dest=/etc/openvpn/server.conf
  
- name: ufw allow 1194 udp
  command: ufw allow 1194/udp
  
- name: ufw set default forward policy
  lineinfile: dest=/etc/default/ufw regexp="^DEFAULT_FORWARD_POLICY" 
    line="DEFAULT_FORWARD_POLICY="ACCEPT""

- name: add openvpn to ufw before.rules
  blockinfile:
    dest: /etc/ufw/before.rules
    marker: "{mark} ANSIBLE MANAGED BLOCK
    insertafter: "#   ufw-before-forward"
    content: |
      # START OPENVPN RULES
      # NAT table rules
      *nat
      :POSTROUTING ACCEPT [0:0] 
      # Allow traffic from OpenVPN client to eth0
      -A POSTROUTING -s 10.8.0.0/8 -o eth0 -j MASQUERADE
      COMMIT
      # END OPENVPN RULES

- name: enable ufw
  command: ufw disable
  
- name: copy easy-rsa certs to openvpn
  copy: src=/etc/easy-rsa/keys/{{ item }} dest=/etc/openvpn remote_src=True owner=root 
    group=root mode=0644
  with_items:
    - "{{ hostname }}.crt"
    - "{{ hostname }}.key"
    - ca.crt
    - dh{{easy_rsa_key_size}}.pem
  notify: openvpn start

- name: copy client certs to openvpn
  copy: src=/etc/easy-rsa/keys/{{ item }} dest=/etc/openvpn remote_src=True owner=root 
    group=root mode=0644
  with_items:
    - "{{ hostname }}.crt"
    - "{{ hostname }}.key"
    - ca.crt
    - dh{{easy_rsa_key_size}}.pem
  notify: openvpn start  

- name: check openvpn status
  service: name=openvpn state=started enabled=yes
  
  - name: generate client certificates and keys
  shell: ". ./vars; ./pkitool {{ item }} >/dev/null"
  args:
    chdir: "{{ easy_rsa_ca_dir }}"
    creates: "{{ easy_rsa_key_dir }}/{{ item }}.key"
  with_items:
    - "{{ list_openvpn_clients }}"

- name: revoke client certificates and keys
  shell: ". ./vars; ./revoke-full {{ item }} >/dev/null"
  args:
    chdir: "{{ easy_rsa_ca_dir }}"
    creates: "{{ easy_rsa_key_dir }}/{{ item }}.pem"
  with_items:
    - "{{ list_openvpn_clients_revoke }}"
    
# Configure OpenVPN Clients GNOME
- name: install depends for network-manager
  apt: name={{ item }} state=present update_cache=true cache_valid_time=86400
  with_items:
    - network-manager-openvpn
    - network-manager-openvpn-gnome
    - network-manager-pptp
    - network-manager-vpnc
  when: "'{{inventory_hostname_short }}' in groups.openvpn-clients"
  
- name: ensure openvpn disabled on startup
  command: update-rc.d openvpn disable
  when: "'{{inventory_hostname_short }}' in groups.openvpn-clients"
  
- name: deploy the network-manager-openvpn-gnome config
  template: src=openvpn-clientconfig.j2 dest=/etc/NetworkManager/system-connection/openvpn
  when: "'{{inventory_hostname_short }}' in groups.openvpn-clients"

  